:%s/“/\&ldquo;/gI
:%s/”/\&rdquo;/gI
:%s/‘/\&lsquo;/gI
:%s/’/\&rsquo;/gI
:%s/—/\&mdash;/gI
:%s/–/\&ndash;/gI
:%s/™/\&trade;/gI
:%s/®/\&reg;/gI
:%s/©/\&copy;/gI
:%s/—/\&mdash;/gI
:%s/–/\&ndash;/gI
:%s/…/\&hellip;/gI

:%s/À/\&Agrave;/gI
:%s/Á/\&Aacute;/gI
:%s/Â/\&Acirc;/gI
:%s/Ã/\&Atilde;/gI
:%s/Ä/\&Auml;/gI
:%s/Å/\&Aring;/gI

:%s/à/\&agrave;/gI
:%s/á/\&aacute;/gI
:%s/â/\&acirc;/gI
:%s/ã/\&atilde;/gI
:%s/ä/\&auml;/gI
:%s/å/\&aring;/gI

:%s/È/\&Egrave;/gI
:%s/É/\&Eacute;/gI
:%s/Ê/\&Ecirc;/gI
:%s/Ë/\&Euml;/gI

:%s/è/\&egrave;/gI
:%s/é/\&eacute;/gI
:%s/ê/\&ecirc;/gI
:%s/ë/\&euml;/gI

:%s/Ì/\&Igrave;/gI
:%s/Í/\&Iacute;/gI
:%s/Î/\&Icirc;/gI
:%s/Ï/\&Iuml;/gI

:%s/ì/\&igrave;/gI
:%s/í/\&iacute;/gI
:%s/î/\&icirc;/gI
:%s/ï/\&iuml;/gI

:%s/Ò/\&Ograve;/gI
:%s/Ó/\&Oacute;/gI
:%s/Ô/\&Ocirc;/gI
:%s/Õ/\&Otilde;/gI
:%s/Ö/\&Ouml;/gI

:%s/ò/\&ograve;/gI
:%s/ó/\&oacute;/gI
:%s/ô/\&ocirc;/gI
:%s/õ/\&otilde;/gI
:%s/ö/\&ouml;/gI

:%s/Ù/\&Ugrave;/gI
:%s/Ú/\&Uacute;/gI
:%s/Û/\&Ucirc;/gI
:%s/Ü/\&Uuml;/gI

:%s/ù/\&ugrave;/gI
:%s/ú/\&uacute;/gI
:%s/û/\&ucirc;/gI
:%s/ü/\&uuml;/gI

:%s/Ñ/\&Ntilde;/gI
:%s/ñ/\&ntilde;/gI

:%s/ß/\&szlig;/gI

